### ISSUE TITLE
help with error

### ISSUE THREAD

**Issue by jmavasa** [protegeproject/protege-plugin-examples#3]
what could be my issue when i get the below error

java.lang.ClassCastException: org.protege.editor.owl.OWLEditorKit cannot be cast to org.protege.editor.owl.OWLEditorKit
    at org.protege.editor.owl.ui.action.ProtegeOWLAction.getOWLEditorKit(ProtegeOWLAction.java:21) ~[protege-editor-owl-5.0.0.jar:na]
    at org.protege.editor.owl.ui.action.ProtegeOWLAction.getOWLModelManager(ProtegeOWLAction.java:26) ~[protege-editor-owl-5.0.0.jar:na]
    at com.agentslab.ame.protege.menu.UnderSubMenu.actionPerformed(UnderSubMenu.java:20) ~[classes/:na]
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_91]
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[na:1.8.0_91]
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_91]
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_91]
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376) ~[na:1.8.0_91]
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833) ~[na:1.8.0_91]
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877) ~[na:1.8.0_91]
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_91]
    at java.awt.Component.processMouseEvent(Component.java:6535) ~[na:1.8.0_91]
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_91]
    at java.awt.Component.processEvent(Component.java:6300) ~[na:1.8.0_91]
    at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_91]
    at java.awt.Component.dispatchEventImpl(Component.java:4891) ~[na:1.8.0_91]
    at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_91]
    at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_91]
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_91]
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[na:1.8.0_91]
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_91]
    at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_91]
    at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_91]
    at java.awt.Component.dispatchEvent(Component.java:4713) ~[na:1.8.0_91]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_91]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_91]
    at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_91]
    at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_91]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_91]
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_91]
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_91]
    at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_91]
    at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_91]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_91]
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.8.0_91]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_91]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_91]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_91]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_91]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_91]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_91]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_91]

after clicking on example tab

**Comment by morteza** [comment]
I've tried to reproduce the bug, but failed to do so; the example plugin works as expected here :-(. It would help if you provide more details on how to reproduce it, your development environment, protege version, java version, etc. (I've compiled and installed it successfully with Protege 5.0.0, Java 1.8.0_05, and maven 3.3.9).

However, it seems the bug is caused by having two different classloaders. You can't cast a class of one classloader, inside another classloader. They are simply different classes (yet similar). You cannot cast a class to itself in this kind of deployment with multiple classloaders.

There are several solutions, mostly should be avoided ([here](http://stackoverflow.com/questions/2371967/java-getting-class-cast-exception-where-both-classes-are-exactly-the-same)). There are several hackings like reflection, class loading, using parent and upper in hierarchy ClassLoader, call ModelManager via `Fields`, reflection using guava, and several others. They are limited, and apparently not-safe. However, I've heard it is a common issue when developing distributed apps.

The problematic casting originated in `org.protege.editor.owl.ui.action.ProtegeOWLAction`, and for the following one:

``` java
public OWLEditorKit getOWLEditorKit() {
  return (OWLEditorKit) getEditorKit();
}
```

I was also reviewing `resources/plugin.xml` file, and `submenu` extension is the only one with a different `editorKitId`. The rest are all set to `any` value. You might want to check that too.

And one more thing: The issue is not related to the submenu or plugin development, but counting OWL object properties. So you can still develop a plugin if it does not use `OWLModelManager` of the Protege. The workaround is to use other libraries to access and manage OWL files, which is not suggested I guess.
